/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodexIndexRouteImport } from './routes/codex/index'
import { Route as CharacterIndexRouteImport } from './routes/character/index'
import { Route as CodexSpeciesRouteImport } from './routes/codex/species'
import { Route as CharacterCharacterIdRouteImport } from './routes/character/$characterId'

const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexIndexRoute = CodexIndexRouteImport.update({
  id: '/codex/',
  path: '/codex/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIndexRoute = CharacterIndexRouteImport.update({
  id: '/character/',
  path: '/character/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexSpeciesRoute = CodexSpeciesRouteImport.update({
  id: '/codex/species',
  path: '/codex/species',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCharacterIdRoute = CharacterCharacterIdRouteImport.update({
  id: '/character/$characterId',
  path: '/character/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/character': typeof CharacterIndexRoute
  '/codex': typeof CodexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/character': typeof CharacterIndexRoute
  '/codex': typeof CodexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/character/$characterId': typeof CharacterCharacterIdRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/character/': typeof CharacterIndexRoute
  '/codex/': typeof CodexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/character/$characterId'
    | '/codex/species'
    | '/character'
    | '/codex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/character/$characterId'
    | '/codex/species'
    | '/character'
    | '/codex'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/character/$characterId'
    | '/codex/species'
    | '/character/'
    | '/codex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  CharacterCharacterIdRoute: typeof CharacterCharacterIdRoute
  CodexSpeciesRoute: typeof CodexSpeciesRoute
  CharacterIndexRoute: typeof CharacterIndexRoute
  CodexIndexRoute: typeof CodexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/': {
      id: '/codex/'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/': {
      id: '/character/'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/species': {
      id: '/codex/species'
      path: '/codex/species'
      fullPath: '/codex/species'
      preLoaderRoute: typeof CodexSpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$characterId': {
      id: '/character/$characterId'
      path: '/character/$characterId'
      fullPath: '/character/$characterId'
      preLoaderRoute: typeof CharacterCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  CharacterCharacterIdRoute: CharacterCharacterIdRoute,
  CodexSpeciesRoute: CodexSpeciesRoute,
  CharacterIndexRoute: CharacterIndexRoute,
  CodexIndexRoute: CodexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
