/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodexIndexRouteImport } from './routes/codex/index'
import { Route as CodexSpeciesRouteImport } from './routes/codex/species'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexIndexRoute = CodexIndexRouteImport.update({
  id: '/codex/',
  path: '/codex/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexSpeciesRoute = CodexSpeciesRouteImport.update({
  id: '/codex/species',
  path: '/codex/species',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/codex': typeof CodexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/codex': typeof CodexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codex/species': typeof CodexSpeciesRoute
  '/codex/': typeof CodexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codex/species' | '/codex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codex/species' | '/codex'
  id: '__root__' | '/' | '/codex/species' | '/codex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodexSpeciesRoute: typeof CodexSpeciesRoute
  CodexIndexRoute: typeof CodexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/': {
      id: '/codex/'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/species': {
      id: '/codex/species'
      path: '/codex/species'
      fullPath: '/codex/species'
      preLoaderRoute: typeof CodexSpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodexSpeciesRoute: CodexSpeciesRoute,
  CodexIndexRoute: CodexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
